#lichesstoken = "OWRX9zHrcSOt8gX9"
lichesstoken = "lip_rPseun7Snplg3SoWuRJg"
#emailaddress = "your@mail.com"
#smtpserver = "smpt.mail.com"
#smtpuser = "name@name.com"
#smtp_encryption = "True"
#smtppassword = "hidden"
#subject = "New PGN file from Centaur"
#fics_server = "fics.freechess.org"
#fics_port = "5000"
#fics_user = "your_fics_username"
#fics_password "your_fics_password"
#icc_server = "chessclub.com"
#fics_port = "5000"
#fics_user = "your_icc_username"
#fics_password "your_icc_password"

